FROM php:7.3
MAINTAINER Dogstudio <developers@dogstudio.be>

${PHP7}

${PHPINI}

RUN pecl install xdebug-2.7.0beta1 \
    && docker-php-ext-enable xdebug
${XDEBUG}

${COMPOSER}

RUN usermod -u 1000 www-data
RUN usermod -a -G users www-data

# App dir
RUN mkdir -p /var/www
WORKDIR /var/www

CMD ["php", "bin/console server:run --docroot=/var/www/dev/public 0.0.0.0:80"]
EXPOSE 80
