FROM php:5.6-apache
MAINTAINER Dogstudio <developers@dogstudio.be>

${PHP5}

${PHPINI}

${XDEBUG}

${COMPOSER}

${APACHE}

# App dir
RUN mkdir -p /var/www
WORKDIR /var/www

RUN usermod -u 1000 www-data && usermod -a -G users www-data

EXPOSE 80 443
