FROM php:7.0
MAINTAINER Dogstudio <developers@dogstudio.be>

${PHP7}

${PHPINI}

${XDEBUG}

${COMPOSER}

RUN usermod -u 1000 www-data && usermod -a -G users www-data

# App dir
RUN mkdir -p /var/www
WORKDIR /var/www

CMD ["php", "bin/console server:run --docroot=/var/www/dev/public 0.0.0.0:80"]
EXPOSE 80
