FROM php:5.6-fpm
MAINTAINER Dogstudio <devs@dogstudio.be>

${PHP5}

${PHPINI}

${XDEBUG}

${COMPOSER}

# App dir
RUN mkdir -p /var/www
WORKDIR /var/www

RUN usermod -u 1000 www-data && usermod -a -G users www-data

CMD ["php-fpm"]
EXPOSE 9000
