FROM php:7.0-apache
MAINTAINER Dogstudio <developers@dogstudio.be>

${PHP7}

${PHPINI}

RUN pecl install xdebug-2.6.0 \
    && docker-php-ext-enable xdebug
${XDEBUG}

${COMPOSER}

${APACHE}

RUN usermod -u 1000 www-data && usermod -a -G users www-data

# App dir
RUN mkdir -p /var/www
WORKDIR /var/www

EXPOSE 80 443
