FROM php:7.3-fpm
MAINTAINER Dogstudio <developers@dogstudio.be>

${PHP7}

${PHPINI}

${XDEBUG}

${COMPOSER}

RUN usermod -u 1000 www-data
RUN usermod -a -G users www-data

# App dir
RUN mkdir -p /var/www
WORKDIR /var/www

CMD ["php-fpm"]
EXPOSE 9000
